Use vanity names for L2 advertisement
openstack-k8s-operators/architecture pull request #64
Opened 2024-01-11 17:40 UTC by leifmadsen

Use the interface vanity names referenced by NNCP within the L2 advertisement configuration.

2024-01-11 18:18 UTC, abays commented
This fixes a problem caused by a combination of hardcoded vanity interface names in the `NNCP` template [1] and the use of the `values.yaml` `data.(internalapi|storage|tenant).iface` in the `L2Advertisement` template for `spec.interfaces.0` [2].  The `L2Advertisement` interface names need to match the vanity interface names created by the `NNCP`.

[1] https://github.com/openstack-k8s-operators/architecture/blob/d1bd4f70ded050463064d929c7342ccbcb660bff/lib/nncp/ocp_node_template.yaml#L26
[2] https://github.com/openstack-k8s-operators/architecture/blob/d1bd4f70ded050463064d929c7342ccbcb660bff/lib/networking/kustomization.yaml#L174-L184

2024-01-11 18:22 UTC, abays commented
Another option is to modify the `NNCP`'s `kustomizational.yaml` to have it consume `data.(internalapi|storage|tenant).iface` [1].  Then the user's choice of interface name is applied globally and we remove the problem caused by the hardcoded interface name in the `NNCP` template.

[1] https://github.com/openstack-k8s-operators/architecture/blob/main/lib/nncp/kustomization.yaml

2024-01-12 13:53 UTC, fultonj commented
+2 makes sense to me.

2024-01-12 18:32 UTC, fultonj commented
> +2 makes sense to me.

This patch should however update both `values.yaml` and `values-ci-framework.yaml`.

2024-01-12 18:32 UTC, fultonj requested changes
Please apply the same change in `values.yaml` to `values-ci-framework.yaml`

2024-01-13 00:33 UTC, fultonj commented
> Please apply the same change in `values.yaml` to `values-ci-framework.yaml`

Apologies,  `values-ci-framework.yaml` already has this change.

I'm OK to merge as-is.

2024-01-15 12:56 UTC, fultonj commented
> Another option is to modify the `NNCP`'s `kustomizational.yaml` to have it consume `data.(internalapi|storage|tenant).iface` [1]. Then the user's choice of interface name is applied globally and we remove the problem caused by the hardcoded interface name in the `NNCP` template.
> 
> [1] https://github.com/openstack-k8s-operators/architecture/blob/main/lib/nncp/kustomization.yaml

I propose we merge this patch as is. We could have a follow up though to do what's described above.

2024-01-15 12:57 UTC, merged